Repository data-umbrella/event-board-web, pull requests merged in 2022-11, with the labels that each got.

#219 Issue #90 Make org name hyper linked styled text
  package-lock.json
  src/components/elements/EventPlanningDetail.jsx
  src/components/elements/EventPlanningSection.jsx
Labels: enhancement

#240 Issue 233 Update Dark Mode Color and Footer Border
  src/App.js
Labels: design

#242 Dark Mode for Search Results View Buttons
  src/components/elements/SearchResultViewSelector.js
  tailwind.config.js
Labels: Search and Filters, easy

#236 Issue 227- Update darkmode for donate button
  src/components/elements/IntroductionSection.jsx
Labels: design, easy

#239 Issue 34: Add asterisks to Event Form
  src/components/elements/EventForm.jsx
  src/components/elements/EventTypeField.jsx
Labels: design, easy

#241 Issue 226: Update About Us Page styles
  src/components/elements/AboutUs.jsx
  src/components/elements/Contributor.jsx
  src/components/pages/AboutPage.jsx
Labels: design, easy

#251 81/calendar hover popup
  package-lock.json
  package.json
  src/App.css
  src/__tests__/components/pages/EventCalendarPage.test.jsx
  src/components/elements/EventCalendarView.jsx
  src/components/elements/MobileNav.jsx
  src/constants/navbar.js
  src/utils/events.js
Labels: Event Calendar Page
