Repository data-umbrella/event-board-web, pull requests merged in 2022-09, with the labels that each got.

#119 Update logo, favicon, and title.
  public/favicon.ico
  public/index.html
  src/assets/logo.png
  src/assets/logo.svg
  src/components/elements/NavigationBar.jsx
Labels: enhancement

#120 Add support for paginated event search results.
  src/hooks/events.js
  src/utils/api.js
Labels: enhancement

#56 Implement List View
  src/__tests__/utils/events.test.js
  src/components/elements/EventListView.jsx
  src/components/elements/EventsForMonth.jsx
  src/hooks/events.js
  src/utils/dates.js
  src/utils/events.js
Labels: enhancement

#121 Implement register link
  src/__tests__/elements/ReviewEventMainSection.test.jsx
  src/components/elements/ReviewEventMainSection.jsx
Labels: bug

#127 Add links to sponsers images.
  src/components/elements/Sponsors.jsx
Labels: enhancement

#130 Install GA tracking package
  package-lock.json
  package.json
  src/App.js
Labels: enhancement

#155 Fix login redirection login.
  src/__tests__/components/pages/VerifyMagicLinkPage.test.jsx
  src/components/pages/VerifyMagicLinkPage.jsx
Labels: Authentication

#157 Temporarily hide weekly digest nav link.
  src/__tests__/elements/NavigationBar.test.jsx
  src/constants/navbar.js
Labels: Navbar

#158 Clean up magic link sign in flow.
  src/__tests__/components/pages/ConfirmRegistrationPage.test.jsx
  src/__tests__/components/pages/MagicLinkSentPage.test.jsx
  src/__tests__/components/pages/RegistrationLinkSentPage.test.jsx
  src/components/elements/AppRoutes.jsx
  src/components/elements/SignInForm.jsx
  src/components/elements/SignUpForm.jsx
  src/components/pages/ConfirmRegistrationPage.jsx
  src/components/pages/MagicLinkSentPage.jsx
  src/components/pages/RegistrationLinkSentPage.jsx
  src/hooks/authentication.js
  src/hooks/query-params.js
Labels: Authentication

#159 Wire up event calendar page
  src/__tests__/components/pages/EventCalendarPage.test.jsx
  src/components/elements/EventCalendarView.jsx
  src/components/elements/EventListView.jsx
  src/components/elements/RegionField.jsx
  src/components/elements/SearchForm.jsx
  src/components/pages/EventCalendarPage.jsx
  src/constants/events.js
  src/hooks/events.js
  src/utils/events.js
Labels: Event Calendar Page

#188 Add links to collectives to about page
  src/components/elements/AboutUs.jsx
Labels: enhancement

#203 Fix mobile nav scroll
  src/components/elements/MobileNav.jsx
  src/index.css
Labels: bug
